family("track_5_numerical")
load("PrgEnv-gnu")
load("nvhpc-mixed")
load("craype-accel-nvidia80")
load("spack-pe-base")
load("cmake")
load("ninja")
load("cray-libsci")
setenv("MPICH_GPU_SUPPORT_ENABLED", 1)
