PETSC_DIR ?= /eagle/ATPESC2025/usr/MathPackages/petsc

CLEANFILES   = rosenbrock4 rosenbrock4cu

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
